<a href="https://colab.research.google.com/github/anajikadam17/Google-Colab/blob/main/NLP/Sentiment_Analysis_with_BERT_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sentiment Analysis with BERT Neural Network


## Data Used
Web Scrap Yelp Website for reviews collection

# 1. Install and Import Dependencies

In [ ]:
!pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |█████████████▌                  | 834.1MB 1.5MB/s eta 0:12:57tcmalloc: large alloc 1147494400 bytes == 0x55af107ec000 @  0x7f48f4665615 0x55aed6f13cdc 0x55aed6ff352a 0x55aed6f16afd 0x55aed7007fed 0x55aed6f8a988 0x55aed6f854ae 0x55aed6f183ea 0x55aed6f8a7f0 0x55aed6f854ae 0x55aed6f183ea 0x55aed6f8732a 0x55aed7008e36 0x55aed6f86853 0x55aed7008e36 0x55aed6f86853 0x55aed7008e36 0x55aed6f86853 0x55aed7008e36 0x55aed708b3e1 0x55aed6feb6a9 0x55aed6f56cc4 0x55aed6f17559 0x55aed6f8b4f8 0x55aed6f1830a 0x55aed6f863b5 0x55aed6f857ad 0x55aed6f183ea 0x55aed6f863b5 0x55aed6f1830a 0x55aed6f863b5
     |█████████████████               | 1055.7MB 1.4MB/s eta 0:11:05tcmalloc: large alloc 1434370048 bytes == 0x55af54e42000 @  0x7f48f4665615 0x55aed6f13cdc 0x55aed6ff352a 0x55aed6f16afd 0x55aed7007fed 0x55aed6f8a988 0x55aed6f854ae 0x55aed6f183ea 0x55aed6f8a7f0 0x55aed6f854ae 0x55aed6f183ea 0x55aed6f8732a 0x55aed7008e36 0x55aed6f86853 0

In [ ]:
!pip install transformers requests beautifulsoup4 pandas numpy

     |████████████████████████████████| 2.5MB 4.1MB/s 
     |████████████████████████████████| 901kB 21.1MB/s 
     |████████████████████████████████| 3.3MB 26.5MB/s 


In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import requests
from bs4 import BeautifulSoup
import re

# 2. Instantiate Model


In [ ]:
# https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment

In [ ]:
tokenizer = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

model = AutoModelForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

# 3. Encode and Calculate Sentiment


In [ ]:
tokens = tokenizer.encode('It was good but couldve been better. Great', return_tensors='pt')


In [ ]:

result = model(tokens)
result.logits


tensor([[-2.7768, -1.2353,  1.4419,  1.9804,  0.4584]],
       grad_fn=<AddmmBackward>)

In [ ]:
tokens


tensor([[  101, 10197, 10140, 12050, 10502, 12296, 10598, 10662, 16197,   119,
         11838,   102]])

In [ ]:
tokens[0]

tensor([  101, 10197, 10140, 12050, 10502, 12296, 10598, 10662, 16197,   119,
        11838,   102])

In [ ]:
tokenizer.decode(tokens[0])

'[CLS] it was good but couldve been better. great [SEP]'

In [ ]:
int(torch.argmax(result.logits))+1

4

# 4. Collect Reviews


[Yelp Website](https://www.yelp.com/biz/social-brew-cafe-pyrmont) for reviews collection 

In [ ]:
r = requests.get('https://www.yelp.com/biz/social-brew-cafe-pyrmont')
soup = BeautifulSoup(r.text, 'html.parser')
regex = re.compile('.*comment.*')
results = soup.find_all('p', {'class':regex})
reviews = [result.text for result in results]

In [ ]:
reviews

['Still one of the favorite coffee shop in Sydney. Staffs have excellent knowledge about beans , flavor, brew skills. They make own pastries which are also tasty too.',
 'I came to Social brew cafe for brunch while exploring the city and on my way to the aquarium. I sat outside. The service was great and the food was good too!I ordered smoked salmon, truffle fries, black coffee and beer.',
 'Good food, pretty good service too.Id recommend this cafe for quick bite',
 'Good coffee and toasts. Straight up and down - hits the spot with nothing mind blowing. Solid and tasty. \xa0Good work',
 "Ricotta hot cakes! These were so yummy. I ate them pretty fast and didn't share with anyone because they were that good ;). I ordered a green smoothie to balance it all out. Smoothie was a nice way to end my brekkie at this restaurant. Others with me ordered the salmon Benedict and the smoked salmon flatbread. They were all delicious and all plates were empty. Cheers!",
 "Ron & Jo are on the go down un

# 5. Load Reviews into DataFrame and Score


In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.array(reviews), columns=['review'])
df['review'].iloc[0]


'Still one of the favorite coffee shop in Sydney. Staffs have excellent knowledge about beans , flavor, brew skills. They make own pastries which are also tasty too.'

In [ ]:
df.head(11)

review
0   Still one of the favorite coffee shop in Sydne...
1   I came to Social brew cafe for brunch while ex...
2   Good food, pretty good service too.Id recommen...
3   Good coffee and toasts. Straight up and down -...
4   Ricotta hot cakes! These were so yummy. I ate ...
5   Ron & Jo are on the go down under and Wow!  We...
6   Great coffee and vibe. That's all  you need. C...
7   Great coffee and vibe. That's all  you need. C...
8   We came for brunch twice in our week-long visi...
9   This is my fave brunch café in and around Sydn...
10  Delicious. The waitress was hot. The burger wa...

In [ ]:
df['review'].iloc[1]

'I came to Social brew cafe for brunch while exploring the city and on my way to the aquarium. I sat outside. The service was great and the food was good too!I ordered smoked salmon, truffle fries, black coffee and beer.'

In [ ]:
def sentiment_score(review):
    tokens = tokenizer.encode(review, return_tensors='pt')
    result = model(tokens)
    return int(torch.argmax(result.logits))+1

sentiment_score(df['review'].iloc[1])

5

In [ ]:
df['review'].iloc[3][:512]

'Good coffee and toasts. Straight up and down - hits the spot with nothing mind blowing. Solid and tasty. \xa0Good work'

In [ ]:
df['sentiment'] = df['review'].apply(lambda x: sentiment_score(x[:512]))


In [ ]:
# 5 : Good to 1 : bad
df

review  sentiment
0   Still one of the favorite coffee shop in Sydne...          5
1   I came to Social brew cafe for brunch while ex...          5
2   Good food, pretty good service too.Id recommen...          4
3   Good coffee and toasts. Straight up and down -...          5
4   Ricotta hot cakes! These were so yummy. I ate ...          5
5   Ron & Jo are on the go down under and Wow!  We...          5
6   Great coffee and vibe. That's all  you need. C...          5
7   Great coffee and vibe. That's all  you need. C...          4
8   We came for brunch twice in our week-long visi...          4
9   This is my fave brunch café in and around Sydn...          5
10  Delicious. The waitress was hot. The burger wa...          4